---
title: "The State of Poverty in the United States"
output: html_document
editor_options: 
  chunk_output_type: console
---

by Ruochen Wang

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = T)

```

```{r load-packages-and-set-wd, echo = T, message = F}
library(tidyverse)
library(readxl)
library(treemapify)
library(extrafont)

setwd("~/Downloads/DataScienceAssignments/dataviz-project")

```

```{r make-time-series, echo = T, message = F}

data_time <-
  read_excel("data/time-pov_rate_by_race.xlsx")

race_eth1 <- c("All Races",
               "Non-Hispanic White",
               "Black",
               "Hispanic",
               "Asian")
data_time$race_eth <- factor(data_time$race_eth, race_eth1)

ggplot() +
  geom_line(data = data_time,
            mapping = aes(x = year,
                          y = pct,
                          color = race_eth)) +
  scale_x_continuous(breaks =
                       c(2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018)) +
  scale_color_brewer(palette = "Set1") +
  theme_minimal() +
  labs(title = "Poverty Trends in the United States, 2009-2018",
       subtitle = "Black and Hispanic populations made the most progress yet still have above-average poverty rates.",
       caption = "Source: US Census Bureau",
       y = "Poverty Rate (%)",
       color = "Race/Ethnicity") +
  theme(plot.margin = unit(c(1,0,1,.5),"cm"),
        plot.title = element_text(size = 14, family = "Arial", face = "bold", vjust = 2),
        plot.subtitle = element_text(size = 9, family = "Arial", vjust = 2),
        plot.caption = element_text(size = 7, family = "Arial", face = "italic", vjust = -4, hjust = 1),
        axis.title.x = element_blank(),
        axis.title.y = element_text(family = "Arial", vjust = 5),
        axis.text.x = element_text(family = "Arial"),
        axis.text.y = element_text(family = "Arial"),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        panel.background = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_line(linetype = "dotted", color = "gray"),
        panel.grid.minor.y = element_blank(),
        axis.line.x = element_line(linetype = "solid", size = .5),
        legend.title = element_text(face = "bold"))

```


```{r make-treemap, echo = T, message = F}

data_treemap <-
  read_excel("data/treemap-snap_and_poverty_rate.xlsx")

ggplot(data = data_treemap,
       mapping = aes(area = est_num_hh_snap,
                     fill = est_pct_hh_poor,
                     label = state,
                     subgroup = census_region)) +
  geom_treemap() +
  geom_treemap_subgroup_border(color = "white") +
  geom_treemap_text(color = "white",
                    place = "center",
                    grow = F,
                    reflow = T) +
  geom_treemap_subgroup_text(color = "#FAFAFA",
                             place = "center",
                             grow = T,
                             alpha = .5,
                             min.size = 0) +
  scale_fill_gradient(low = "#c6dbef", high = "#08306b",
                      limits = c(5, 25),
                      breaks = seq(5, 25, by = 5),
                      name = "% of Households Experienced\nPoverty in the Past 12 Months") +
  labs(title = "Number of Households Receiving SNAP Benefits, 2017",
       subtitle = "Southern states, where poverty is the most concentrated among census regions, held the most families receiving food stamps\nin 2017.",
       caption = "Source: 2017 American Community Survey 5-Year Estimates, US Census Bureau") +
  theme(plot.margin = unit(c(1,0,1,0),"cm"),
        plot.title = element_text(size = 14, family = "Arial", face = "bold", vjust = 2),
        plot.subtitle = element_text(size = 9, family = "Arial", vjust = 2),
        plot.caption = element_text(size = 7, family = "Arial", face = "italic", vjust = -2, hjust = 0),
        legend.title = element_text(size = 7, family = "Arial", vjust = 4),
        legend.text = element_text(size = 7, family = "Arial"))

```


```{r make-bar, echo = T, message = F}

data_bar <-
  read_excel("data/bar-pov_rate_by_ed.xls")

ggplot() +
  geom_col(data = data_bar,
           mapping = aes(x = reorder(ed_level, -pct),
                         y = pct),
           fill = "#fdbe85",
           color = "#fdbe85",
           width = .7) +
  geom_hline(yintercept = 11.4697, size = .7, linetype = "dashed", color = "#8c2d04") +
  scale_y_continuous(breaks = c(0, 5, 10, 15, 20, 25)) +
  labs(title = "In the United States, high school dropouts are almost twice as likely to experience\npoverty as their peers with a high school diploma",
       subtitle = "Percent of US Population 25 Years and Older Living Below Poverty Level in the Past 12 Months, 2017",
       caption = "* Dashed line denotes national average.\nSource: 2017 American Community Survey 5-Year Estimates, US Census Bureau",
       y = "%") +
  theme_minimal() +
  theme(plot.margin = unit(c(1,0,1,0),"cm"),
        plot.title = element_text(size = 12, family = "Arial", face = "bold", vjust = 3),
        plot.subtitle = element_text(size = 9, family = "Arial", vjust = 3),
        plot.caption = element_text(size = 7, family = "Arial", face = "italic", vjust = -2, hjust = 0),
        axis.title.x = element_blank(),
        axis.title.y = element_text(angle = 0, family = "Arial", vjust = .5),
        axis.text.x = element_text(angle = 45, vjust = 1.1, hjust = 1, family = "Arial"),
        axis.text.y = element_text(family = "Arial"),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        panel.background = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())

```


```{r make-reg, echo = T, message = F, warning = F}

data_reg <-
  read_excel("data/reg-pov_rate_by_sex.xlsx")

ggplot(data = data_reg,
       mapping = aes(x = pct_collgrad, y = pct_pov, color = Gender)) +
  geom_smooth(method = lm, se = F) +
  geom_text(aes(label = abbr), size = 2.5, family = "Arial", show.legend = F) +
  scale_x_continuous(limits = c(20, 60), breaks = (c(20, 30, 40, 50, 60))) +
  scale_y_continuous(limits = c(7, 23), breaks = (c(7, 9, 11, 13, 15, 17, 19, 21, 23))) +
  scale_color_brewer(palette = "Set1") +
  labs(title = "The Gender Gap in Educational Attainment and Poverty",
       subtitle = "Women are more likely to experience poverty than men with similar education levels. The poverty reduction\neffect of education is also greater for men than for women.",
       caption = "Source: 2017 American Community Survey 5-Year Estimates, US Census Bureau",
       x = "Percent of Population 18 to 24 Years Enrolled in College or Graduate School, 2017",
       y = "Percent of Population Living Below Poverty Level\nin the Past 12 Months, 2017") +
  theme_bw() +
  theme(plot.margin = unit(c(1,0,1,.5),"cm"),
        plot.title = element_text(size = 14, family = "Arial", face = "bold", vjust = 2),
        plot.subtitle = element_text(size = 9, family = "Arial", vjust = 2),
        plot.caption = element_text(size = 7, family = "Arial", face = "italic", vjust = -4, hjust = 0),
        axis.title.x = element_text(size = 7, family = "Arial",vjust = -1),
        axis.title.y = element_text(size = 7, family = "Arial",vjust = 3),
        axis.text.x = element_text(family = "Arial"),
        axis.text.y = element_text(family = "Arial"),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        legend.title = element_text(face = "bold"))

```
